export const USER_LOGIN = {
    REQUEST:"USER_LOGIN_REQUEST_LOAD",
    SUCCESS:"USER_LOGIN_SUCCESS_LOAD",
    FAIL:"USER_LOGIN_FAIL_LOAD",
}

export const USER_REGISTER = {
    REQUEST:"USER_REGISTER_REQUEST_LOAD",
    SUCCESS:"USER_REGISTER_SUCCESS_LOAD",
    FAIL:"USER_REGISTER_FAIL_LOAD",
}

export const USER_FETCH = {
    REQUEST:"USER_FETCH_REQUEST_LOAD",
    SUCCESS:"USER_FETCH_SUCCESS_LOAD",
    FAIL:"USER_FETCH_FAIL_LOAD",
}

export const UPDATE_IMAGE = {
    REQUEST:"UPDATE_IMAGE_REQUEST_LOAD",
    SUCCESS:"UPDATE_IMAGE_SUCCESS_LOAD",
    FAIL:"UPDATE_IMAGE_FAIL_LOAD",
}

export const LOGOUT_USER = "LOGOUT_USER"


export const GET_PRAYERS_USER = {
    REQUEST:"GET_PRAYERS_USER_REQUEST_LOAD",
    SUCCESS:"GET_PRAYERS_USER_SUCCESS_LOAD",
    FAIL:"GET_PRAYERS_USER_FAIL_LOAD",
}

export const GET_GALLERY_IMAGES = {
    REQUEST:"GET_GALLERY_IMAGES_REQUEST_LOAD",
    SUCCESS:"GET_GALLERY_IMAGES_SUCCESS_LOAD",
    FAIL:"GET_GALLERY_IMAGES_FAIL_LOAD",
}
