export const USER_LOGIN = {
    REQUEST:"USER_LOGIN_REQUEST",
    SUCCESS:"USER_LOGIN_SUCCESS",
    FAIL:"USER_LOGIN_FAIL",
}

export const USER_REGISTER = {
    REQUEST:"USER_REGISTER_REQUEST",
    SUCCESS:"USER_REGISTER_SUCCESS",
    FAIL:"USER_REGISTER_FAIL",
}

export const USER_FETCH = {
    REQUEST:"USER_FETCH_REQUEST",
    SUCCESS:"USER_FETCH_SUCCESS",
    FAIL:"USER_FETCH_FAIL",
}

export const UPDATE_IMAGE = {
    REQUEST:"UPDATE_IMAGE_REQUEST",
    SUCCESS:"UPDATE_IMAGE_SUCCESS",
    FAIL:"UPDATE_IMAGE_FAIL",
}

export const LOGOUT_USER = "LOGOUT_USER"


export const GET_PRAYERS_USER = {
    REQUEST:"GET_PRAYERS_USER_REQUEST",
    SUCCESS:"GET_PRAYERS_USER_SUCCESS",
    FAIL:"GET_PRAYERS_USER_FAIL",
}

export const GET_GALLERY_IMAGES = {
    REQUEST:"GET_GALLERY_IMAGES_REQUEST",
    SUCCESS:"GET_GALLERY_IMAGES_SUCCESS",
    FAIL:"GET_GALLERY_IMAGES_FAIL",
}
