export const ADMIN_LOGIN = {
  REQUEST: "ADMIN_LOGIN_REQUEST_LOAD",
  SUCCESS: "ADMIN_LOGIN_SUCCESS_LOAD",
  FAIL: "ADMIN_LOGIN_FAIL_LOAD",
};

export const ADD_USER = {
  REQUEST: "ADD_USER_REQUEST_LOAD",
  SUCCESS: "ADD_USER_SUCCESS_LOAD",
  FAIL: "ADD_USER_FAIL_LOAD",
};

export const GET_USERS = {
  REQUEST: "GET_USERS_REQUEST_LOAD",
  SUCCESS: "GET_USERS_SUCCESS_LOAD",
  FAIL: "GET_USERS_FAIL_LOAD",
};


export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
