export const ADMIN_LOGIN = {
  REQUEST: "ADMIN_LOGIN_REQUEST_LOAD",
  SUCCESS: "ADMIN_LOGIN_SUCCESS_LOAD",
  FAIL: "ADMIN_LOGIN_FAIL_LOAD",
};

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

export const ADD_USER = {
  REQUEST: "ADD_USER_REQUEST_LOAD",
  SUCCESS: "ADD_USER_SUCCESS_LOAD",
  FAIL: "ADD_USER_FAIL_LOAD",
};

export const GET_USERS = {
  REQUEST: "GET_USERS_REQUEST_LOAD",
  SUCCESS: "GET_USERS_SUCCESS_LOAD",
  FAIL: "GET_USERS_FAIL_LOAD",
};

export const GET_ADMINS = {
  REQUEST: "GET_ADMINS_REQUEST_LOAD",
  SUCCESS: "GET_ADMINS_SUCCESS_LOAD",
  FAIL: "GET_ADMINS_FAIL_LOAD",
};

export const CREATE_ADMIN = {
  REQUEST: "CREATE_ADMIN_REQUEST_LOAD",
  SUCCESS: "CREATE_ADMIN_SUCCESS_LOAD",
  FAIL: "CREATE_ADMIN_FAIL_LOAD",
};


export const GET_PRAYERS = {
  REQUEST: "GET_PRAYERS_REQUEST_LOAD",
  SUCCESS: "GET_PRAYERS_SUCCESS_LOAD",
  FAIL: "GET_PRAYERS_FAIL_LOAD",
};

export const CREATE_PRAYER = {
  REQUEST: "CREATE_PRAYER_REQUEST_LOAD",
  SUCCESS: "CREATE_PRAYER_SUCCESS_LOAD",
  FAIL: "CREATE_PRAYER_FAIL_LOAD",
};

export const EDIT_PRAYER = {
  REQUEST: "EDIT_PRAYER_REQUEST_LOAD",
  SUCCESS: "EDIT_PRAYER_SUCCESS_LOAD",
  FAIL: "EDIT_PRAYER_FAIL_LOAD",
};

export const GET_IMAGES = {
  REQUEST: "GET_IMAGES_REQUEST_LOAD",
  SUCCESS: "GET_IMAGES_SUCCESS_LOAD",
  FAIL: "GET_IMAGES_FAIL_LOAD",
};

export const UPLOAD_IMAGE = {
  REQUEST: "UPLOAD_IMAGE_REQUEST_LOAD",
  SUCCESS: "UPLOAD_IMAGE_SUCCESS_LOAD",
  FAIL: "UPLOAD_IMAGE_FAIL_LOAD",
};

export const ADD_SCC = {
  REQUEST: "ADD_SCC_REQUEST_LOAD",
  SUCCESS: "ADD_SCC_SUCCESS_LOAD",
  FAIL: "ADD_SCC_FAIL_LOAD",
};