export const USER_LOGIN = {
    REQUEST:"USER_LOGIN_REQUEST_LOAD",
    SUCCESS:"USER_LOGIN_SUCCESS_LOAD",
    FAIL:"USER_LOGIN_FAIL_LOAD",
}

export const USER_REGISTER = {
    REQUEST:"USER_REGISTER_REQUEST_LOAD",
    SUCCESS:"USER_REGISTER_SUCCESS_LOAD",
    FAIL:"USER_REGISTER_FAIL_LOAD",
}

export const USER_FETCH = {
    REQUEST:"USER_FETCH_REQUEST_LOAD",
    SUCCESS:"USER_FETCH_SUCCESS_LOAD",
    FAIL:"USER_FETCH_FAIL_LOAD",
}

export const LOGOUT_USER = "LOGOUT_USER"
